email: dev@lhy.kr
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site Settings
locale                   : "en-US"
title                    : "lhy's blog"
title_separator          : "|"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "lhy"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://lhy.kr"
baseurl: ""
repository: "LeeHanYeong/LeeHanYeong.github.io"
breadcrumbs: true
search: true
words_per_minute: 200
comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"

# SEO / Analytics
google_site_verification: "cccQDzXIUT2HeSQayd01Hyr9Ods4mdJ3Yml2_0khq6E"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-EZZPDGYZJT"

# Site Author
author:
  name             : "lhy"
  avatar           : "/assets/images/profile.jpg"
  bio              : "Django programmer"
  location         : "Seongnam, Korea"
  links:
    - label: "LeeHanYeong"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LeeHanYeong"
    - label: "dev@lhy.kr"
      icon: "far fa-fw fa-envelope"
      url: "mailto:dev@lhy.kr"
    - label: "lhy.kr"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/lhy.kr"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/hanyeong-lee-03256590"

# Site Footer
footer:
  links:
    - label: ""
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LeeHanYeong"
    - label: ""
      icon: "fab fa-fw fa-instagram"
      url: https://instagram.com/lhy.kr

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
paginate: 5
paginate_path: /page:num/
timezone: Asia/Seoul

# Plugins
plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: "_posts/programming"
      type: posts
    values:
      layout: single
      author_profile: true
      classes: wide
      permalink: ":title"
      show_date: true
      read_time: true
      comments: true
      share: true
      related: true